### ISSUE TITLE
docker build error, failing test of python gdal library

### ISSUE THREAD

**Issue by yosukefk** [yosukefk/finn_preproc#46]
Dockerfile has `conda install gdal`, then it test if install was success.  Getting following error.

The same error with [earlier version of Dockerfile ](https://github.com/yosukefk/finn_preproc/blob/05ce56866118791c64ea05a845ca704666599029/Dockerfile) , where @mbjoseph has extra specifics for version/repository of anaconda python, or the [latest version](https://github.com/yosukefk/finn_preproc/blob/f89e4ed10a8ddd5d496077ddec455b85aa7deafc/Dockerfile).

> Step 9/15 : RUN python -c 'from osgeo import gdal'
>  ---> Running in d01d3f8f9339
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/opt/conda/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in <module>
>     _gdal = swig_import_helper()
>   File "/opt/conda/lib/python3.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
>     _mod = imp.load_module('_gdal', fp, pathname, description)
>   File "/opt/conda/lib/python3.7/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/opt/conda/lib/python3.7/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: /opt/conda/lib/python3.7/site-packages/osgeo/../../.././libkea.so.1.4: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxB5cxx11Ey
> The command '/bin/sh -c python -c 'from osgeo import gdal'' returned a non-zero code: 1

**Comment by yosukefk** [comment]
These may be related
https://github.com/conda-forge/gdal-feedstock/issues/201
https://conda-forge.org/docs/user/tipsandtricks.html

**Comment by yosukefk** [comment]
Or this one...
https://github.com/conda-forge/gdal-feedstock/issues/275

@mbjoseph , I thought your Dockerfile was meant to prevent this kind of issue caused by cutting-edge version of library, is it right?  Is it possible to pin us down to a certain, stable/release version of conda library?

**Comment by yosukefk** [comment]
#47
